# Generated by Django 5.2 on 2026-07-22 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('optimizer', '0008_alter_prompthistory_optimization_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimizer_name', models.CharField(choices=[('aiven', 'Aiven Prompt Optimizer'), ('promptoptimizer', 'PromptOptimizer.tools')], max_length=50)),
                ('optimized_prompt', models.TextField()),
                ('optimized_input_tokens', models.PositiveIntegerField(default=0)),
                ('optimized_output_tokens', models.PositiveIntegerField(default=0)),
                ('optimized_total_tokens', models.PositiveIntegerField(default=0)),
                ('tokens_saved', models.PositiveIntegerField(default=0)),
                ('semantic_accuracy', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('optimization_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('estimated_cost_saved', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('processing_time', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='optimizer.prompthistory')),
            ],
            options={
                'verbose_name': 'Comparison History',
                'verbose_name_plural': 'Comparison Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
