# Generated by Django 5.2 on 2026-07-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonhistory',
            name='optimized_input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comparisonhistory',
            name='optimized_output_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comparisonhistory',
            name='optimized_total_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comparisonhistory',
            name='tokens_saved',
            field=models.IntegerField(default=0),
        ),
    ]
