# Generated by Django 5.2 on 2026-07-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison1', '0002_alter_comparisonhistory_optimized_input_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonhistory',
            name='optimized_prompt_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
