# Generated by Django 5.2.17 on 2026-09-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison1', '0003_comparisonhistory_optimized_prompt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonhistory',
            name='optimizer_name',
            field=models.CharField(choices=[('aiven', 'Aiven Prompt Optimizer'), ('prompt-opt', 'PromptOpt'), ('numstack', 'NumStack Prompt Optimizer')], max_length=50),
        ),
    ]
