"""
Base LLM Adapter

Every LLM provider must inherit from this class and implement
the required methods.

Supported Providers (Future):
- Gemini
- Ollama
- OpenAI
- Claude
- Mistral
"""

from abc import ABC, abstractmethod


class BaseLLMAdapter(ABC):
    """
    Abstract base class for all LLM adapters.
    """

    @abstractmethod
    def optimize(self, prompt: str) -> dict:
        """
        Optimize a prompt using the underlying LLM.

        Parameters:
            prompt (str): Prompt generated by PromptBuilder.

        Returns:
            dict:
            {
                "success": bool,
                "provider": str,
                "model": str,
                "optimized_prompt": str,
                "error": str | None
            }
        """
        pass