# Generated by Django 5.2 on 2026-07-04 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimized_prompt', models.TextField(blank=True, null=True)),
                ('ai_model', models.CharField(choices=[('gpt-4o', 'GPT-4o'), ('gpt-4.1', 'GPT-4.1'), ('gemini', 'Gemini'), ('claude', 'Claude'), ('deepseek', 'DeepSeek'), ('llama', 'Llama')], max_length=20)),
                ('optimization_level', models.CharField(choices=[('light', 'Light'), ('balanced', 'Balanced'), ('aggressive', 'Aggressive')], default='balanced', max_length=20)),
                ('original_tokens', models.PositiveIntegerField(default=0)),
                ('optimized_tokens', models.PositiveIntegerField(default=0)),
                ('tokens_saved', models.PositiveIntegerField(default=0)),
                ('estimated_cost_saved', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('processing_time', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
