# Generated by Django 5.2 on 2026-07-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0002_prompthistory_original_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompthistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
