# Generated by Django 5.2 on 2026-07-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0003_prompthistory_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompthistory',
            old_name='optimized_tokens',
            new_name='optimized_input_tokens',
        ),
        migrations.RenameField(
            model_name='prompthistory',
            old_name='original_tokens',
            new_name='optimized_output_tokens',
        ),
        migrations.AddField(
            model_name='prompthistory',
            name='optimized_total_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prompthistory',
            name='original_input_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prompthistory',
            name='original_output_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prompthistory',
            name='original_total_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prompthistory',
            name='tokens_saved',
            field=models.IntegerField(default=0),
        ),
    ]
