# Generated by Django 5.2 on 2026-07-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0004_rename_optimized_tokens_prompthistory_optimized_input_tokens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompthistory',
            name='ai_model',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4o'), ('gpt-4.1', 'GPT-4.1'), ('gemini', 'Gemini'), ('claude', 'Claude'), ('deepseek', 'DeepSeek'), ('llama', 'Llama')], max_length=100),
        ),
    ]
