# Generated by Django 5.2 on 2026-07-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0005_alter_prompthistory_ai_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompthistory',
            name='ai_model',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4o'), ('gpt-4.1', 'GPT-4.1'), ('gemini', 'Gemini'), ('claude', 'Claude'), ('deepseek', 'DeepSeek'), ('llama', 'Llama'), ('gemini-3.1-flash-lite', 'Gemini-3.1-Flash-Lite'), ('gemini-2.5-flash', 'Gemini-2.5-Flash-Lite'), ('gemini-2.5-pro', 'Gemini-2.5-Pro'), ('gemini-2.0-flash', 'Gemini-2.0-Flash'), ('gemini-2.0-flash-lite', 'Gemini-2.0-Flash-Lite')], max_length=100),
        ),
    ]
