# Generated by Django 5.2 on 2026-07-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0006_alter_prompthistory_ai_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompthistory',
            name='optimization_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='prompthistory',
            name='quality_rating',
            field=models.CharField(default='Good', max_length=20),
        ),
        migrations.AddField(
            model_name='prompthistory',
            name='semantic_accuracy',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
