# Generated by Django 5.2 on 2026-07-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0007_prompthistory_optimization_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompthistory',
            name='optimization_score',
            field=models.FloatField(default=0),
        ),
    ]
